name = "productivity-assistant-worker"
main = "src/index.ts"
compatibility_date = "2024-06-01"
compatibility_flags = ["nodejs_compat"]

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "productivity-db"
database_id = "3bfde29c-eff5-4a2c-9f7e-544c78849f4e"
migrations_dir = "db/migrations"

[vars]
ENV = "development"
